package com.google.android.gms.ads.internal;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.location.Location;
import android.os.Bundle;
import com.google.android.gms.internal.zzaaa;
import com.google.android.gms.internal.zzaev;
import com.google.android.gms.internal.zzaiy;
import com.google.android.gms.internal.zzajg;
import com.google.android.gms.internal.zzis;
import com.google.android.gms.internal.zziw;
import com.google.android.gms.internal.zzla;
import com.google.android.gms.internal.zzlw;
import com.google.android.gms.internal.zznd;
import com.google.android.gms.internal.zzoc;
import com.google.android.gms.internal.zzom;
import com.google.android.gms.internal.zzzz;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.Future;
import org.json.JSONArray;
import org.json.JSONObject;

final class zzbc implements Callable<zzoc> {
    private /* synthetic */ zzaev zzana;
    private /* synthetic */ zzba zzaqs;
    private /* synthetic */ int zzaqt;
    private /* synthetic */ JSONArray zzaqu;
    private /* synthetic */ int zzaqv;

    zzbc(zzba zzba, int i, JSONArray jSONArray, int i2, zzaev zzaev) {
        this.zzaqs = zzba;
        this.zzaqt = i;
        this.zzaqu = jSONArray;
        this.zzaqv = i2;
        this.zzana = zzaev;
    }

    public final /* synthetic */ Object call() throws Exception {
        if (this.zzaqt >= this.zzaqu.length()) {
            return null;
        }
        JSONArray jSONArray = new JSONArray();
        jSONArray.put(r0.zzaqu.get(r0.zzaqt));
        JSONObject jSONObject = new JSONObject();
        jSONObject.put("ads", jSONArray);
        zza zzba = new zzba(r0.zzaqs.zzamt.zzaif, r0.zzaqs.zzamw, r0.zzaqs.zzamt.zzath, r0.zzaqs.zzamt.zzatb, r0.zzaqs.zzanb, r0.zzaqs.zzamt.zzatd, true);
        zzba.zza(r0.zzaqs.zzamt, zzba.zzamt);
        zzba.zzdj();
        zzba.zza(r0.zzaqs.zzamp);
        zznd zznd = zzba.zzamo;
        int i = r0.zzaqt;
        zznd.zzf("num_ads_requested", String.valueOf(r0.zzaqv));
        zznd.zzf("ad_index", String.valueOf(i));
        zzzz zzzz = r0.zzana.zzcpe;
        String jSONObject2 = jSONObject.toString();
        Bundle bundle = zzzz.zzclo.extras != null ? new Bundle(zzzz.zzclo.extras) : new Bundle();
        bundle.putString("_ad", jSONObject2);
        int i2 = zzzz.zzclo.versionCode;
        long j = zzzz.zzclo.zzbbv;
        int i3 = zzzz.zzclo.zzbbw;
        List list = zzzz.zzclo.zzbbx;
        boolean z = zzzz.zzclo.zzbby;
        int i4 = zzzz.zzclo.zzbbz;
        boolean z2 = zzzz.zzclo.zzbca;
        String str = zzzz.zzclo.zzbcb;
        zzlw zzlw = zzzz.zzclo.zzbcc;
        Location location = zzzz.zzclo.zzbcd;
        String str2 = zzzz.zzclo.zzbce;
        zzlw zzlw2 = zzlw;
        String str3 = str2;
        zzis zzis = new zzis(i2, j, bundle, i3, list, z, i4, z2, str, zzlw2, location, str3, zzzz.zzclo.zzbcf, zzzz.zzclo.zzbcg, zzzz.zzclo.zzbch, zzzz.zzclo.zzbci, zzzz.zzclo.zzbcj, zzzz.zzclo.zzbck);
        Bundle bundle2 = zzzz.zzcln;
        zziw zziw = zzzz.zzath;
        String str4 = zzzz.zzatb;
        ApplicationInfo applicationInfo = zzzz.applicationInfo;
        PackageInfo packageInfo = zzzz.zzclp;
        String str5 = zzzz.zzclr;
        String str6 = zzzz.zzcls;
        zzaiy zzaiy = zzzz.zzatd;
        Bundle bundle3 = zzzz.zzclt;
        List list2 = zzzz.zzaub;
        List list3 = zzzz.zzcmd;
        Bundle bundle4 = zzzz.zzclv;
        zza zza = zzba;
        boolean z3 = zzzz.zzclw;
        int i5 = zzzz.zzclx;
        int i6 = zzzz.zzcly;
        float f = zzzz.zzaxd;
        String str7 = zzzz.zzclz;
        Bundle bundle5 = bundle3;
        List list4 = list2;
        long j2 = zzzz.zzcma;
        String str8 = zzzz.zzcmb;
        List list5 = zzzz.zzcmc;
        String str9 = zzzz.zzata;
        zzom zzom = zzzz.zzatt;
        String str10 = zzzz.zzcmf;
        float f2 = zzzz.zzcmg;
        boolean z4 = zzzz.zzcmm;
        int i7 = zzzz.zzcmh;
        int i8 = zzzz.zzcmi;
        boolean z5 = zzzz.zzcmj;
        boolean z6 = zzzz.zzcmk;
        Bundle bundle6 = bundle4;
        Future zzi = zzajg.zzi(zzzz.zzcml);
        String str11 = zzzz.zzcmn;
        boolean z7 = z6;
        boolean z8 = zzzz.zzcbz;
        int i9 = zzzz.zzcmo;
        Bundle bundle7 = zzzz.zzcmp;
        String str12 = zzzz.zzcmq;
        zzla zzla = zzzz.zzatv;
        boolean z9 = zzzz.zzcmr;
        Bundle bundle8 = zzzz.zzcms;
        List list6 = list3;
        zzis zzis2 = zzis;
        PackageInfo packageInfo2 = packageInfo;
        String str13 = str5;
        str3 = str6;
        zzaiy zzaiy2 = zzaiy;
        Bundle bundle9 = bundle5;
        List list7 = list4;
        boolean z10 = z3;
        int i10 = i5;
        int i11 = i6;
        float f3 = f;
        String str14 = str7;
        long j3 = j2;
        String str15 = str8;
        List list8 = list5;
        String str16 = str9;
        zzom zzom2 = zzom;
        String str17 = str10;
        float f4 = f2;
        boolean z11 = z4;
        int i12 = i7;
        int i13 = i8;
        boolean z12 = z5;
        boolean z13 = z7;
        zza zza2 = zza;
        zza2.zza(new zzaaa(bundle2, zzis2, zziw, str4, applicationInfo, packageInfo2, str13, str3, zzaiy2, bundle9, list7, list6, bundle6, z10, i10, i11, f3, str14, j3, str15, list8, str16, zzom2, str17, f4, z11, i12, i13, z12, z13, zzi, str11, z8, i9, bundle7, str12, zzla, z9, bundle8, zzzz.zzcmw, zzajg.zzi(zzzz.zzclq), zzzz.zzatx, zzzz.zzcmx, zzzz.zzcmy, 1, zzzz.zzcna, zzzz.zzcnb), zza2.zzamo);
        return (zzoc) zza2.zzdl().get();
    }
}
